const SET_USER_DATA_ACTION = `SET_USER_DATA_ACTION`;
const RESET_USER_ACTION = `RESET_USER_ACTION`;
const SET_BATTLE_BTN_ACTION = `SET_BATTLE_BTN_ACTION`;

export{SET_USER_DATA_ACTION, RESET_USER_ACTION,SET_BATTLE_BTN_ACTION};